# Generated by Django 5.2.8 on 2025-11-19 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_number', models.CharField(max_length=100, unique=True, verbose_name='Номер аудитории')),
                ('classroom_type', models.CharField(choices=[('computer', 'Компьютерный'), ('lecture', 'Лекционный')], max_length=50, verbose_name='Тип аудитории')),
                ('capacity', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['classroom_number'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('group_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=10, verbose_name='Тип группы')),
                ('group_course', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['group_course', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО преподавателя')),
                ('lesson_type', models.CharField(choices=[('practical', 'Практический'), ('lecture', 'Лекционный')], max_length=50, verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('lesson_time', models.IntegerField(choices=[(0, '08:00'), (1, '09:00'), (2, '10:00'), (3, '11:00'), (4, '12:00'), (5, '13:00'), (6, '14:00'), (7, '15:00'), (8, '16:00'), (9, '17:00'), (10, '18:00')], verbose_name='Время занятия')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.classroom', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'lesson_time'],
                'unique_together': {('classroom', 'day_of_week', 'lesson_time'), ('group', 'day_of_week', 'lesson_time'), ('teacher', 'day_of_week', 'lesson_time')},
            },
        ),
    ]
